rv-brand = "ReVanced"

[TikTok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
included-patches = "'SIM spoof'"
build-mode = "apk"

[YT]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = "'Custom branding'"
build-mode = "apk"

[YTMusic]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "arm64-v8a"
build-mode = "apk"

[Twitch]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"
build-mode = "apk"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
included-patches = "'Open links with app chooser'"
build-mode = "apk"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
build-mode = "apk"

[YTMusic-Extended]
app-name = "YTMusic"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "Extended"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "arm64-v8a"

[YT-Extended]
app-name = "YT"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "Extended"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube" 
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Reddit-Extended]
app-name = "Reddit"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "Extended"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
